import { cn } from "@/lib/utils";
import "@/styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import { Toaster as SonnerToaster } from "@/components/ui/sonner";
import Providers from "./Providers";
import { ThemeSync } from "@/components/app-theme-sync-component";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Assistcx",
  description: "Generated by Aexonic Technologies Pvt Ltd",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          inter.className
        )}
      >
        <Toaster />
        <SonnerToaster position="top-center" />
        <Providers>
          <ThemeSync />
          {children}
        </Providers>
      </body>
    </html>
  );
}
