export const INITIAL_TOOL_DATA = {
  id: "",
  name: "",
  action: "",
  function: "",
  description: "",
  api_type: "",
  method: "",
  endpoint: "",
  content_type: "",
  body_template: "",
  headers: {},
  path_params: {},
  query_params: {},
  auth_config: {
    username: "",
    password: "",
    token: "",
    client_id: "",
    client_secret: "",
    token_url: "",
    scope: "",
    api_key_name: "",
    api_key: "",
    api_key_location: "",
  },
  icon: "",
  auth_type: "",
  is_default: false,
};

export const DEFAULT_FORM_VALUES = {
  name: "",
  protocol: "REST",
  action: "",
  description: "",
  api_type: "REST" as "REST" | "ODATA" | "SOAP",
  body_template: "",
  endpoint: "",
  content_type: "",
  icon: "tool-case",
  username: "",
  password: "",
  token: "",
  client_id: "",
  client_secret: "",
  token_url: "",
  scope: "",
  api_key_name: "",
  api_key: "",
  api_key_location: "header",
  auth_type: "",
};

export const apiTypes = [
  { id: "api_rest", value: "REST", label: "REST API" },
  { id: "api_odata", value: "ODATA", label: "ODATA API" },
  { id: "api_soap", value: "SOAP", label: "SOAP API" },
];
